name: dimipay_kiosk
description: "디미페이 키오스크"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 2.0.0+39

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  dio: ^5.4.0
  camera: ^0.10.5+9
  lottie: ^3.1.0
  flutter_svg: ^2.0.10+1
  dimipay_design_kit:
    git:
      url: https://github.com/dimipay/dimipay_design_kit.git
      ref: main
  intl: ^0.19.0
  flutter_secure_storage: ^9.2.2
  cryptography: ^2.7.0
  fast_rsa: ^3.6.4
  jwt_decoder: ^2.0.1
  uuid: ^4.4.2
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  archive: ^3.6.1
  popover: ^0.3.1
  image: ^4.2.0
  convert_native_img_stream: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.12
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/cards/

  fonts:
    - family: SUITv1
      fonts:
        - asset: assets/fonts/SUITv1-Thin.ttf
          weight: 100
        - asset: assets/fonts/SUITv1-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/SUITv1-Light.ttf
          weight: 300
        - asset: assets/fonts/SUITv1-Regular.ttf
          weight: 400
        - asset: assets/fonts/SUITv1-Medium.ttf
          weight: 500
        - asset: assets/fonts/SUITv1-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SUITv1-Bold.ttf
          weight: 700
        - asset: assets/fonts/SUITv1-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/SUITv1-Heavy.ttf
          weight: 900